apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: flask-hpa
  name: flask-hpa
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 5000
  selector:
    app: flask-hpa
  type: NodePort
status:
  loadBalancer: {}
